"""empty message

Revision ID: f07b2eeff5c2
Revises: 6120e9e00bda
Create Date: 2021-08-03 10:09:31.781081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f07b2eeff5c2'
down_revision = '6120e9e00bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contagiados',
    sa.Column('DNI', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Nombre', sa.String(length=250), nullable=True),
    sa.Column('Apellido', sa.String(length=250), nullable=True),
    sa.Column('Edad', sa.Integer(), nullable=True),
    sa.Column('Sexo', sa.String(length=25), nullable=True),
    sa.Column('Obra_social', sa.String(length=250), nullable=True),
    sa.Column('Asistencia', sa.String(length=5), nullable=True),
    sa.Column('Telefono', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(length=250), nullable=True),
    sa.Column('Domicilio', sa.String(length=250), nullable=True),
    sa.Column('Barrio', sa.String(length=250), nullable=True),
    sa.Column('Fecha_positivo', sa.String(length=250), nullable=True),
    sa.Column('Variante', sa.String(length=250), nullable=True),
    sa.Column('Fecha_primerosSintomas', sa.String(length=250), nullable=True),
    sa.Column('Sintomas', sa.String(length=250), nullable=True),
    sa.Column('Comorbilidad', sa.String(length=250), nullable=True),
    sa.Column('Fecha_alta', sa.String(length=250), nullable=True),
    sa.Column('Fecha_muerte', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('DNI')
    )
    op.drop_table('datos_contagiados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_contagiados',
    sa.Column('DNI', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Apellido', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Edad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sexo', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('Obra_social', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Asistencia', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('Telefono', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Domicilio', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Barrio', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Fecha_positivo', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Variante', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Fecha_primerosSintomas', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Sintomas', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Comorbilidad', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Fecha_alta', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Muerte', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Fecha_muerte', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('DNI'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('contagiados')
    # ### end Alembic commands ###
